### ISSUE TITLE
test_pipeline.py: TNS query returns 403 Forbidden

### ISSUE THREAD

**Issue by HeloiseS** [tarxiv/tarxiv#25]
### 💡  To try
It's possible that GH censors the secrets when they are put into the pay load. **Need to figure out what the censoring policy is and how to pass API keys to be used in integration tests during CI**.

🤯 **NOTE:** It's a 403 not a 401! So it's not unauthenticated, it's **unauthorised**. Authnetication may be fine! But for some reason TNS doesn't allow us to proceed with the request. Not sure what to make of it, but probably a clue. 
↪ _**This may be a red herring**_ We have authentication errors with the ATLAS etc.. when we mock the TNS results (see in the What we've tried section).

### ❌  What we've tried 
1. Added the API keys as environment variables in GH secrets and tested they are actually understood by the CI using:
```yaml
   - name: Debug secrets
      run: |
        echo "TNS API Key is: ${TARXIV_TNS_API_KEY}"
        python -c "import os; print('From Python:', os.environ.get('TARXIV_TNS_API_KEY'))"
```

Indeed returns *** as expected (GH doesn't show the secrets)

2. Tried removing references to the config file by hard coding values of rate limit, name, site, etc...
Didn't do anything - this is not surprising, we did try to make sure our path to the config file was set correctly at the top of the file with 
```python
PATH = os.path.join(os.path.dirname(__file__), "../../aux")
``` 

3. Tried mocking TNS ra and dec but ATLAS and the rest fall over as well: **NOT JUST TNS ISSUE**. General problem with creating the headers with the right authentication form the CI.

4. Print in the logs the TNS ID we get from the secrets to see what comes out: ***. **It censors it EVERYTIME!**
